/**
These are the cards that weren't automatically roped in and should be generated by hand.
**/
#include <string>

#include "BgBaseCard.hpp"
#include "BgCardFactory.hpp"
BgBaseCard BgCardFactory::get_card(std::string name) {
    try {
	return BgBaseCardFactory::get_card(name);
    }
    catch (std::runtime_error&) {
	// TODO: Change this to be unordered map
	if (name == "Foe Reaper 4000") {
	    return BgBaseCard(6, "NEUTRAL", 8, 9, "Foe Reaper 9000", "Foe Reaper 9000", "['CLEAVE']",
			      "MECHANICAL", "LEGENDARY", 6, "", "MINION");
	}
	else {
	    throw std::runtime_error("No card has name " + name);
	}
    }
}
