/**
These are the cards that weren't automatically roped in and should be generated by hand.
**/
#include <string>
#include <unordered_map>

#include "BgBaseCard.hpp"
#include "BgCardFactory.hpp"
BgBaseCard BgCardFactory::get_card(std::string name) {
    try {
	return BgBaseCardFactory::get_card(name);
    }
    catch (std::runtime_error&) {
	auto card_found_it = cards.find(name);
	if (card_found_it == cards.end())  {
	    throw std::runtime_error("No card has name " + name);
	}
	else {
	    return card_found_it->second;
	}
    }
}

void BgCardFactory::init_cards() {
    auto card = BgBaseCard(6, "NEUTRAL", 8, 9,
			   "Foe Reaper 4000",
			   "Foe Reaper 4000", "['CLEAVE']",
			   "MECHANICAL", "LEGENDARY", 6, "", "MINION");
    cards.emplace("Foe Reaper 4000", card);
}
